### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by waalge** [mlabs-haskell/plutus-contract#1]
Is there a reason the apache license was taken out?

**Comment by L-as** [comment]
Complete oversight

**Comment by MangoIV** [comment]
Sorry for that. Will fix asap. Please mind that this is still WIP and will need a bit of fixing.

**Comment by waalge** [comment]
:) don't worry - I've been here long enough to know the drill

**Comment by MangoIV** [comment]
Fixed :+1:
